### PR TITLE
Update CLI version

### PR DESCRIPTION
**Pull request by pranavkm**
cc @muratg \ @davidfowl  \ @ryanbrandenburg

### CODE REVIEW

**Comment by davidfowl** [comment]
:shipit:  it works right?

**Comment by Eilon** [comment]
Yeah we ran UniverseCoherence on it. We had to abandon the gate because we couldn't take a new CoreFX due to the Registry/Windows change.

**Comment by ryanbrandenburg** [comment]
:shipit:

**Comment by pranavkm** [comment]
Yes. We had a UniverseCoherence build that worked with this.

**Pull request merged**
