### PR TITLE
Restore reference assemblies in xplat

### PR DESCRIPTION
**Pull request by pranavkm**
cc @victorhurdugaci \ @pakrym \ @anurse

### CODE REVIEW

**Comment by pranavkm** [comment]
This is required for https://github.com/aspnet/Logging/pull/448

**Comment by pakrym** [comment]
Can we call the package `NETFrameworkReferenceAssemblies` to be a bit more specific?
Otherwise :shipit:

**Comment by natemcmaster** [comment]
Just curious. Have we looked into using the official targeting pack nupkgs? 

https://dotnet.myget.org/feed/dotnet-core/package/nuget/Microsoft.TargetingPack.NETFramework.v4.5.1

**Comment by pranavkm** [comment]
Oh nifty - didn't realize they had a package we could target. I'll give that one a try

**Comment by natemcmaster** [comment]
Actually, I just tried it on Microsoft.Data.Sqlite. It doesn't seem to work :-/

**Comment by pranavkm** [comment]
@natemcmaster could you file a CoreFx bug for it so that we can eventually move to their package.

**Comment by natemcmaster** [comment]
https://github.com/dotnet/corefx/issues/9735

**Comment by pakrym** [comment]
There is no CLI support for this. We still can use this package same way we used our own.

**Comment by pranavkm** [comment]
Yeah, looks like it. In our case, we don't reference the package but treat it as the search space for reference assemblies. Maybe doing something similar works just fine?

**Comment by pranavkm** [comment]
Their structure is kinda crummy - `/Microsoft.TargetingPack.NETFramework.v4.5.1/1.0.1/lib/net451` has binaries in it whereas `DOTNET_REFERENCE_ASSEMBLIES_PATH` maps to `C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework`. We'd have to move `net451` -> `.NETFramework/v.4.5.1` something our package already preserves. @natemcmaster do you feel strongly about switching to this package? If not we can live with what we have which seems to be working fine so far.

**Comment by natemcmaster** [comment]
No, it looks the like the packages aren't really ready for use anywhere than in corefx's build system. They're kinda working on making it possible, but it's not ready yet.

**Pull request merged**
