### PR TITLE
Honor AdditionalProperties metadata on ProjectsToTest items

### PR DESCRIPTION
**Pull request by bricelam**
@smitpatel and I want to use [this feature](https://msdn.microsoft.com/en-us/library/z7f65y0d.aspx#Anchor_5), but the task batching prevents it.

### CODE REVIEW

**Comment by natemcmaster** [comment]
Haha, you and I were on the same wavelength. I made a PR a few minutes ago with the same thing #236.

**Comment by bricelam** [comment]
Great minds do indeed think alike.

**Comment by bricelam** [comment]
lol, or we've been equally jaded by MSBuild 😉

**Comment by natemcmaster** [comment]
I've come to love the dark magic that is MSBuild

**Pull request closed without merging**
