### PR TITLE
Remove dnx

### PR DESCRIPTION
**Pull request by victorhurdugaci**
DNX is now an opt in:smile: 

@pranavkm @davidfowl

### CODE REVIEW

**Comment by davidfowl** [comment]
:shipit:

**Comment by pranavkm** [comment]
:shipit:

**Comment by victorhurdugaci** [comment]
Updated to remove dnx completely

**Comment by natemcmaster** [comment]
:+1: Fixes https://github.com/aspnet/KoreBuild/issues/7

**Pull request merged**
