### PR TITLE
Update CLI versions to 1.0.0-preview2-003121

### LINKED ISSUE #113: KoreBuild with .NET Core 1.0.1
Is it possible to update KoreBuild to use `1.0.0-preview2-003131` (1.0.1)? Could we bump the `cli.version.*` guys?

### PR DESCRIPTION
**Pull request by henkmollema**
This updates the CLI version in the `cli.version.*` to the new .NET Core 1.0.1 release: 1.0.0-preview2-003121.

Fixes #113

### CODE REVIEW

**Comment by troydai** [comment]
Looks good to me. /cc @pranavkm

**Comment by muratg** [comment]
@pranavkm Are you covering this with your changes?

**Comment by pranavkm** [comment]
Not as yet. We're using the 3121 CLI in the gate branch. I think we should fine taking this in independently since this was an patch release. I'll self assign and get this in

**Comment by henkmollema** [comment]
@pranavkm I can rebase if you want.

**Comment by henkmollema** [comment]
@anurse already did this: 45b1eec7064568d1a70bf6e9bde3955cf5f24698.

**Comment by analogrelay** [comment]
Whoops! I didn't see your PR or I'd have accepted it rather than making the change myself :). Sorry about that! Thanks for noticing the change!

**Comment by henkmollema** [comment]
No worries! Glad it got fixed. 😄

**Pull request closed without merging**
