### PR TITLE
Remove Sake

### PR DESCRIPTION
**Pull request by natemcmaster**
Resolves https://github.com/aspnet/KoreBuild/issues/174

The only target using this was NuGetInstall, but with changes @pranavkm is making to Universe (https://github.com/aspnet/Universe/pull/478), we won't need that target anymore.

Close https://github.com/aspnet/KoreBuild/issues/137

### CODE REVIEW

**Review by pranavkm — APPROVED** [review]
👋

**Comment by davidfowl** [comment]
Can I build without mono now?

**Comment by natemcmaster** [comment]
Yes. We can start adding `mono: none` to our travis.yml files as well.

**Comment by davidfowl** [comment]
Lets verify that 😄

**Pull request merged**
