### PR TITLE
Remove dotnet.exe from shared directory to workaround cli issue

### PR DESCRIPTION
**Pull request by pakrym**
https://github.com/dotnet/cli/issues/2143

### CODE REVIEW

**Comment by pranavkm** [comment]
:shipit: does this fix the issue?

**Comment by pakrym** [comment]
Removing it localy fixed the issue

**Comment by victorhurdugaci** [comment]
:shipit: after you add a comment with a link to the issue or an explanation so that we know why this workaround was added and when to remove it.

**Comment by davidfowl** [comment]
What about the .sh? Is that broken as well?

**Comment by pakrym** [comment]
I don't know exactly there are other blockers on non win so i didn't get to this one.

**Comment by pranavkm** [comment]
Cross plat has the same issues

**Comment by davidfowl** [comment]
Is it being fixed in the same way

**Pull request merged**
