### PR TITLE
Use FLOWID if specified when logging messages

### PR DESCRIPTION
**Pull request by pranavkm**

### CODE REVIEW

**Comment by davidfowl** [comment]
huh?

**Comment by pranavkm** [comment]
It might make reporting parallel builds a bit easier to read. No idea if it actually works though.

**Comment by muratg** [comment]
Who sets the env var?  Looks like a useful addition to me.

**Comment by pranavkm** [comment]
The Batch build in Universe would make use of it - https://github.com/aspnet/Universe/pull/411/files#diff-9c69ad97a4a478903e84088c363feebaR963

**Pull request closed without merging**
