### PR TITLE
update to LTS released SDK version

### PR DESCRIPTION
**Pull request by analogrelay**
/cc @Eilon @pranavkm

### CODE REVIEW

**Comment by pranavkm** [comment]
:shipit:  (Need to update the tag too)

**Comment by analogrelay** [comment]
Tag updated.

**Comment by henkmollema** [comment]
@anurse looks like your change is undone by @BrennanConroy  in the 1.0.0 tag: 579071cfbda8ff4dcae0ecdebebb381f9f66920c.

**Comment by pranavkm** [comment]
Thanks for noticing this @henkmollema. Fixed the issue.

**Comment by henkmollema** [comment]
Thanks!

**Pull request merged**
