### PR TITLE
Use a different target name for Restore

### PR DESCRIPTION
**Pull request by pranavkm**
Fixes https://github.com/aspnet/KoreBuild/issues/177

Unblocks https://github.com/aspnet/Coherence/pull/169

### CODE REVIEW

**Comment by natemcmaster** [comment]
FYI, the alternate solution I have proposed in https://github.com/aspnet/KoreBuild/pull/180 is that we keep "Restore", but that don't override it in the standard lifecycle.

**Comment by pranavkm** [comment]
That ends up including quite a bit more changes to make `_LoadRestoreGraphEntryPoints` work. Let's do this since it's small. Once we merge your changes in, it should continue working without any changes.

**Comment by natemcmaster** [comment]
Ok. :shipit:

**Comment by natemcmaster** [comment]
Yo, one more thing to fix. https://github.com/aspnet/KoreBuild/blob/feature/msbuild/build/shade/_k-standard-goals.shade#L88

**Pull request merged**
