### PR TITLE
Stop setting .net reference assemblies path on bash

### PR DESCRIPTION
**Pull request by troydai**
https://github.com/dotnet/cli/issues/531 is closed.

@victorhurdugaci @pranavkm

### CODE REVIEW

**Comment by victorhurdugaci** [comment]
Looks good and you have a :shipit: from me but you cannot merge it until we pick a new CLI

**Comment by troydai** [comment]
When will we pick a new CLI?

**Comment by victorhurdugaci** [comment]
Hopefully next week when we get a build that doesn't AV. @Eilon was talking over email with some folks who actively work on that

**Comment by Eilon** [comment]
We tried to take a new CLI today but we ran into some issues. We'll try again on Monday.

**Comment by troydai** [comment]
Got it. I'll wait.

**Comment by muratg** [comment]
Can we check this in yet?

**Comment by troydai** [comment]
@victorhurdugaci may I merge it now? Who's the build buddy this week? They shall be aware of this, too. The impact is limited to non-Windows platforms.

**Comment by muratg** [comment]
@troydai build buddies are @moozzyk and @Tratcher

**Comment by troydai** [comment]
/cc @moozzyk @Tratcher @victorhurdugaci 
I'm ready merge this change. Can any one you green light it?

**Comment by victorhurdugaci** [comment]
I'm okay with the chance assuming the CLI we're using has Troy's fix :shipit:

**Comment by troydai** [comment]
@moozzyk @Tratcher please note that I merged this change. Should you see and errors from Linux and Unix indicate build error under desktop CLR, please free feel to let me know.

**Comment by moozzyk** [comment]
@troydai - thanks for the heads up.

**Pull request merged**
