### PR TITLE
Use build globbing for tests and samples

### PR DESCRIPTION
**Pull request by pakrym**
Should go in only after we get CLI with memory caching.

@pranavkm

### CODE REVIEW

**Comment by pranavkm** [comment]
@pakrym does the current CLI support this?

**Comment by pakrym** [comment]
Yes

**Comment by pakrym** [comment]
But I need to make sure before merging that everything works.

**Comment by pranavkm** [comment]
So little faith in your own code :smirk_cat:

**Comment by pakrym** [comment]
Tried on couple repos, seems to work fine.

**Pull request merged**
